version: '3'

services:
  nginxServer:
    container_name: nginxServer
    image: nginx:1.13.5-alpine
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/var/www/html/index.php
      - ./application:/var/www/html/application
      - ./system:/var/www/html/system
      - ./application/assets:/var/www/html/application/assets
      - ./composer.json:/var/www/html/composer.json
      - ./.htaccess:/var/www/html/.htaccess
    links:
      - php7
  
  php7:
    container_name: php7
    image: php:7-fpm
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
    volumes:
      - ./docker/php/php.ini:/etc/php/php.ini
      - ./index.php:/var/www/html/index.php
      - ./application:/var/www/html/application
      - ./system:/var/www/html/system
      - ./application/assets:/var/www/html/application/assets
      - ./composer.json:/var/www/html/composer.json
      - ./.htaccess:/var/www/html/.htaccess
